import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const workspaceUrl = new URL('../../workspace.js', import.meta.url);
const adminUrl = new URL('../../admin/index.html', import.meta.url);
const adminUiUrl = new URL('../../admin/admin-ui.js', import.meta.url);
const teacherUrl = new URL('../../teacher/index.html', import.meta.url);
const workspaceCssUrl = new URL('../../workspace.css', import.meta.url);

test('private educator upload controls use the same source and narration field names as the server', async () => {
  const [workspace, admin, teacher, adminUi] = await Promise.all([readFile(workspaceUrl, 'utf8'), readFile(adminUrl, 'utf8'), readFile(teacherUrl, 'utf8'), readFile(adminUiUrl, 'utf8')]);
  assert.match(admin, /name="audioFile"/);
  assert.match(admin, /name="sectionId"/);
  assert.match(admin, /data-narration-section-hint/);
  assert.match(admin, /data-mcq-draft-form/);
  assert.match(admin, /data-assessment-draft-form/);
  assert.match(admin, /data-open-assessment-draft/);
  assert.match(admin, /data-publish-assessment-draft/);
  assert.match(admin, /data-download-source/);
  assert.match(admin, /data-admin-source-form/);
  assert.match(admin, /Upload and prepare course/);
  assert.match(admin, /data-workspace-nav="source"/);
  assert.match(admin, /data-workspace-nav="builder"/);
  assert.match(admin, /data-workspace-nav="tools"/);
  assert.match(admin, /data-workspace-nav="assessments"/);
  assert.match(admin, /data-panel="source"/);
  assert.match(admin, /data-panel="builder"/);
  assert.match(admin, /data-panel="tools"/);
  assert.match(admin, /data-panel="assessments"/);
  assert.match(admin, /data-admin-slot="source"/);
  assert.match(admin, /data-admin-slot="builder"/);
  assert.match(adminUi, /const organiseAdministratorWorkspace/);
  assert.match(adminUi, /\[data-admin-source-form\]/);
  assert.match(adminUi, /\[data-markdown-form\]/);
  assert.match(adminUi, /\[data-ai-draft-form\]/);
  assert.match(adminUi, /\[data-assessment-draft-form\]/);
  assert.match(adminUi, /\[data-mcq-draft-form\]/);
  assert.match(adminUi, /templateButton/);
  assert.match(adminUi, /openCourseReviewButton/);
  assert.match(admin, /data-admin-source-progress/);
  assert.match(admin, /data-open-editable-course-review/);
  assert.match(admin, /class="admin-source-progress-spinner"/);
  assert.match(admin, /application\/pdf/);
  assert.match(admin, /\.pptx/);
  assert.match(admin, /data-convert-source/);
  assert.match(admin, /Convert extracted source to reviewed Markdown/);
  assert.match(admin, /data-authoring-jump="source"/);
  assert.match(admin, /data-authoring-anchor="form"/);
  assert.match(admin, /data-authoring-anchor="markdown"/);
  assert.match(workspace, /course-authoring-form\.js/);
  assert.match(workspace, /data-build-and-validate-course/);
  assert.match(workspace, /data-authoring-jump/);
  assert.match(workspace, /Build &amp; validate course/);
  assert.match(workspace, /<select data-builder-field="\$\{language\}\.typingLevel"/);
  assert.doesNotMatch(workspace, /typingLevel: 'اہم خیال لکھنا'/);
  assert.match(workspace, /typingLevel !== 'Recall typing' && !typingTarget/);
  assert.doesNotMatch(workspace, /typingTarget: need\(`\$\{prefix\}\.typingTarget/);
  assert.match(admin, /data-open-course-review/);
  assert.match(admin, /data-generate-narration/);
  assert.match(admin, /Recommended route/);
  assert.match(admin, /Optional replacement/);
  assert.match(admin, /admin-narration-route--human/);
  assert.match(admin, /data-translation-form/);
  assert.match(admin, /Generated banks require a configured reviewer/);
  assert.match(admin, /name="distractor3"/);
  assert.match(workspace, /form\.get\('sourceFile'\)\?\.size/);
  assert.match(workspace, /form\.get\('audioFile'\)\?\.size/);
  assert.doesNotMatch(workspace, /form\.get\('audio'\)\?\.size/);
  assert.match(workspace, /window\.open\(destination\.href/);
  assert.match(workspace, /courseId', course\.courseId/);
  assert.match(workspace, /form\.get\('answer'\)/);
  assert.match(workspace, /distractors: \['distractor1', 'distractor2', 'distractor3'\]/);
  assert.match(workspace, /\/api\/v1\/assessment\/drafts/);
  assert.match(workspace, /\/api\/v1\/assessment\/publish/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/source-download/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/source-convert/);
  assert.match(workspace, /type2learn:admin-source-added/);
  assert.match(workspace, /Source text was extracted privately\. Type2Learn is preparing a reviewed Markdown draft now/);
  assert.match(workspace, /const submittedForm = event\.currentTarget/);
  assert.doesNotMatch(workspace, /event\.currentTarget\.reset\(\)/);
  assert.match(workspace, /startSourceConversion\(submissionId, \{ autoPreview: true \}\)/);
  assert.match(workspace, /compileCurrentMarkdown\(\{ preview: true \}\)/);
  assert.match(workspace, /show\('source'\);/);
  assert.match(workspace, /data-open-editable-course-review/);
  assert.match(workspace, /const openEditableCourseReview = async/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/review\?courseId=/);
  assert.doesNotMatch(workspace, /Continue in learner course<\/button>/);
  const adminSourceHandler = workspace.slice(workspace.indexOf("$('[data-admin-source-form]')"), workspace.indexOf('const bindAuthoring'));
  assert.ok(adminSourceHandler.indexOf("setAdminSourceProgress(extracted ? 'extracting'") < adminSourceHandler.indexOf("window.dispatchEvent(new CustomEvent('type2learn:admin-source-added'"));
  assert.ok(adminSourceHandler.indexOf("window.dispatchEvent(new CustomEvent('type2learn:admin-source-added'") < adminSourceHandler.lastIndexOf('await loadSubmissions();'));
  assert.match(workspace, /\/api\/v1\/course-authoring\/translate/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/review/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/narration\/generate/);
  assert.match(workspace, /data-edit-module/);
  assert.match(workspace, /data-source-file-summary/);
  assert.match(workspace, /data-source-next-step/);
  assert.match(workspace, /data-delete-course/);
  assert.match(workspace, /course-authoring\/course', \{ method: 'DELETE'/);
  assert.match(workspace, /Type DELETE to remove this course version/);
  assert.match(workspace, /authoringBrief/);
  assert.match(workspace, /safe-presentation-text-extracted/);
  assert.match(workspace, /Open and review a draft before publishing it/);
  assert.match(workspace, /correctOptionIndex/);
  assert.doesNotMatch(workspace, /prompt: 'Which answer best matches the reviewed key idea\?'/);
  assert.match(teacher, /<body data-workspace="teacher" class="workspace-auth-pending">/);
  assert.match(teacher, /data-workspace-gate/);
  assert.match(teacher, /application\/pdf/);
  assert.match(teacher, /\.pptx/);
  assert.match(teacher, /name="learningGoal"/);
  assert.match(teacher, /name="sourceLanguage"/);
  assert.match(teacher, /data-source-file-summary/);
  assert.match(teacher, /data-source-next-step/);
  assert.match(admin, /data-delete-course/);
  assert.match(admin, /Remove a course version/);
  assert.match(admin, /workspace\.js\?v=20260903-admin-sections1/);
  assert.match(teacher, /workspace\.js\?v=20260903-admin-sections1/);
});

test('source conversion preserves the fast draft path, detailed timing evidence, and heavy repair only when structure needs it', async () => {
  const service = await readFile(new URL('../../server/course-authoring-service.mjs', import.meta.url), 'utf8');
  assert.match(service, /heavy: purpose === 'course-authoring-repair'/);
  assert.match(service, /timeoutMs: purpose === 'course-authoring-conversion' \? 12_000 : 18_000/);
  assert.match(service, /durationMs: Math\.max\(0, Date\.now\(\) - conversionStartedMs\)/);
  assert.match(service, /durationMs: Math\.max\(0, Date\.now\(\) - stageStartedMs\)/);
});

test('private PDF intake has a visible accessible progress state and a reduced-motion-safe spinner', async () => {
  const [admin, css] = await Promise.all([readFile(adminUrl, 'utf8'), readFile(new URL('../../admin/admin.css', import.meta.url), 'utf8')]);
  assert.match(admin, /role="status" aria-live="polite"/);
  assert.match(css, /admin-source-progress-spinner/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
  assert.match(css, /admin-source-progress-spin/);
});

test('teacher navigation keeps every primary route visible on a narrow screen', async () => {
  const [teacher, css] = await Promise.all([readFile(teacherUrl, 'utf8'), readFile(workspaceCssUrl, 'utf8')]);
  assert.match(teacher, /data-workspace-nav="overview"/);
  assert.match(teacher, /data-workspace-nav="submit"/);
  assert.match(teacher, /data-workspace-nav="learners"/);
  assert.match(teacher, /data-workspace-nav="distribution"/);
  assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.workspace-nav \{ display: grid; grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); overflow: visible;/);
});
