import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const workspaceUrl = new URL('../../workspace.js', import.meta.url);
const adminUrl = new URL('../../admin/index.html', import.meta.url);

test('private educator upload controls use the same source and narration field names as the server', async () => {
  const [workspace, admin] = await Promise.all([readFile(workspaceUrl, 'utf8'), readFile(adminUrl, 'utf8')]);
  assert.match(admin, /name="audioFile"/);
  assert.match(admin, /name="sectionId"/);
  assert.match(admin, /data-narration-section-hint/);
  assert.match(admin, /data-mcq-draft-form/);
  assert.match(admin, /data-assessment-draft-form/);
  assert.match(admin, /data-open-assessment-draft/);
  assert.match(admin, /data-publish-assessment-draft/);
  assert.match(admin, /data-download-source/);
  assert.match(admin, /data-admin-source-form/);
  assert.match(admin, /application\/pdf/);
  assert.match(admin, /data-open-course-review/);
  assert.match(admin, /data-generate-narration/);
  assert.match(admin, /Recommended route/);
  assert.match(admin, /Optional replacement/);
  assert.match(admin, /admin-narration-route--human/);
  assert.match(admin, /data-translation-form/);
  assert.match(admin, /Generated banks require a configured reviewer/);
  assert.match(admin, /name="distractor3"/);
  assert.match(workspace, /form\.get\('sourceFile'\)\?\.size/);
  assert.match(workspace, /form\.get\('audioFile'\)\?\.size/);
  assert.doesNotMatch(workspace, /form\.get\('audio'\)\?\.size/);
  assert.match(workspace, /window\.open\(destination\.href/);
  assert.match(workspace, /courseId', course\.courseId/);
  assert.match(workspace, /form\.get\('answer'\)/);
  assert.match(workspace, /distractors: \['distractor1', 'distractor2', 'distractor3'\]/);
  assert.match(workspace, /\/api\/v1\/assessment\/drafts/);
  assert.match(workspace, /\/api\/v1\/assessment\/publish/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/source-download/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/translate/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/review/);
  assert.match(workspace, /\/api\/v1\/course-authoring\/narration\/generate/);
  assert.match(workspace, /data-edit-module/);
  assert.match(workspace, /Open and review a draft before publishing it/);
  assert.match(workspace, /correctOptionIndex/);
  assert.doesNotMatch(workspace, /prompt: 'Which answer best matches the reviewed key idea\?'/);
});
